services:
  nginx:
    image: nginx:latest
    container_name: marslog-nginx
    ports:
      - "8885:80"
    volumes:
      - ./app/frontend:/var/www/html
      - ./app/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/logs/nginx:/var/log/nginx
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.2-fpm
    container_name: marslog-php
    volumes:
      - ./app/frontend:/var/www/html
      - ./app/docker/php-optimization/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped

  flask-api:
    build:
      context: ./app/docker/flask-api
      dockerfile: Dockerfile
    container_name: marslog-flask
    network_mode: "host"
    volumes:
      - ./app/backend:/app
      - ./app/data/monitoring:/app/data/monitoring
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: marslog-clickhouse
    volumes:
      - ./app/docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/docker/clickhouse/users.xml:/etc/clickhouse-server/users.d/marslog_users.xml
      - ./app/data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
    restart: unless-stopped
    network_mode: "host"

  redis:
    image: redis:7-alpine
    container_name: marslog-redis
    command: redis-server --save "" --appendonly no --maxmemory 100mb --maxmemory-policy allkeys-lru
    volumes:
      - ./app/data/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  clickhouse-data:
  redis-data:
